apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ template "airflow.fullname" . }}-main'
data:
  airflow.cfg: |-
  airflow-init.sh: |-
    airflow initdb && \
    (airflow create_user -u airflow -l airflow -f jon -e airflow@apache.org -r Admin -p airflow || true)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ template "airflow.fullname" . }}-worker'
data:
  airflow.cfg: |-
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch.fullname" . }}
data:
  elasticsearch.yml: |-
    path:
      logs: /usr/share/elasticsearch/logs
      data: /usr/share/elasticsearch/data
    cluster.name: {{ .Values.elasticsearch.cluster.name }}
    processors: ${PROCESSORS:}
    network.host: 0.0.0.0
    node.name: ${HOSTNAME}

  log4j2.properties: |-
    status = error
    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n
    rootLogger.level = info
    rootLogger.appenderRef.console.ref = console
    logger.searchguard.name = com.floragunn
    logger.searchguard.level = info
