apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "elasticsearch.fullname" .  }}
  labels:
    module: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app: es
spec:
  serviceName: {{ template "elasticsearch.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      module: {{ template "airflow.name" . }}
      release: {{ .Release.Name }}
      app: es
  template:
    metadata:
      labels:
        module: {{ template "airflow.name" . }}
        release: {{ .Release.Name }}
        app: es
    spec:
      initContainers:
      - name: "sysctl"
        image: "busybox"
        imagePullPolicy: "Always"
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: "chown"
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy | quote }}
        command:
        - /bin/bash
        - -c
        - chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data &&
          chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/logs
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
        - mountPath: /usr/share/elasticsearch/logs
          name: logs
      containers:
      - name: es
        env:
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Xms{{ .Values.elasticsearch.heapSize }} -Xmx{{ .Values.elasticsearch.heapSize }}"
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
        - mountPath: /usr/share/elasticsearch/config/log4j2.properties
          name: config
          subPath: log4j2.properties
        livenessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        resources:
{{ toYaml .Values.elasticsearch.resources | indent 10 }}
    {{- with .Values.elasticsearch.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.elasticsearch.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.elasticsearch.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "elasticsearch.fullname" . }}
  {{- if not .Values.elasticsearch.persistence.data.enabled }}
      - name: data
        emptyDir: {}
  {{ end }}
  {{- if not .Values.elasticsearch.persistence.logs.enabled }}
      - name: logs
        emptyDir: {}
  {{ end }}
  {{- if or .Values.elasticsearch.persistence.logs.enabled .Values.elasticsearch.persistence.data.enabled }}
  volumeClaimTemplates:
  {{- if .Values.elasticsearch.persistence.data.enabled }}
  {{- with .Values.elasticsearch.persistence.data }}
  - metadata:
      name: data
    spec:
      accessModes:
        - {{ .accessMode | quote }}
    {{- if .storageClass }}
    {{- if (eq "-" .storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .storageClass }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: "{{ .size }}"
  {{ end }}
  {{ end }}
  {{- if .Values.elasticsearch.persistence.logs.enabled }}
  {{- with .Values.elasticsearch.persistence.logs }}
  - metadata:
      name: logs
    spec:
      accessModes:
        - {{ .accessMode | quote }}
    {{- if .storageClass }}
    {{- if (eq "-" .storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .storageClass }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: "{{ .size }}"
  {{ end }}
  {{ end }}
  {{ end }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    module: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.fullname" . }}
spec:
  clusterIP: None
  ports:
    - name: transport
      port: 9300
      targetPort: transport
    - name: http
      port: 9200
      targetPort: http
  selector:
    module: {{ template "airflow.name" . }}
    release: {{ .Release.Name }}
    app: es
