kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: '{{ template "airflow.fullname" .  }}-scheduler'
  labels:
    module: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      module: {{ template "airflow.name" . }}
      release: {{ .Release.Name }}
      app: scheduler
  template:
    metadata:
      labels:
        module: {{ template "airflow.name" . }}
        release: {{ .Release.Name }}
        app: scheduler
    spec:
    {{- with .Values.master.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      containers:
      - name: scheduler
        image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}"
        imagePullPolicy: {{ .Values.master.image.pullPolicy }}
        args: ["airflow", "scheduler"]
        env:
        - name: AIRFLOW_KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
      {{- if .Values.logging_backend.nfs.enable }}
        - name: logs
          mountPath: /root/airflow/logs
      {{ end }}
        - name: airflow-configmap
          mountPath: /root/airflow/airflow.cfg
          subPath: airflow.cfg
        - name: dags
          mountPath: /root/airflow/dags
      volumes:
    {{- if .Values.logging_backend.nfs.enable }}
      - name: logs
        persistentVolumeClaim:
          claimName: '{{ template "airflow.fullname" . }}-logs'
    {{ end }}
      - name: dags
        persistentVolumeClaim:
          claimName: '{{ template "airflow.fullname" . }}-dags'
      - name: airflow-configmap
        configMap:
          name:  '{{ template "airflow.fullname" . }}'
