kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: '{{ template "airflow.fullname" .  }}-webserver'
  labels:
    module: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      module: {{ template "airflow.name" . }}
      release: {{ .Release.Name }}
      app: webserver
  template:
    metadata:
      labels:
        module: {{ template "airflow.name" . }}
        release: {{ .Release.Name }}
        app: webserver
      initContainers:
      - name: "init"
        image: ccr.ccs.tencentyun.com/apache/airflow:dev
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: airflow-configmap
          mountPath: /root/airflow/airflow.cfg
          subPath: airflow.cfg
        - name: airflow-configmap
          mountPath: /tmp/airflow-init.sh
          subPath: airflow-init.sh
        - name: dags
          mountPath: /root/airflow/dags
        command:
          - "bash"
        args:
          - "-cx"
          - "/tmp/airflow-init.sh"
      containers:
      - name: webserver
        image: "{{ .Values.airflow.main.image.repository }}:{{ .Values.airflow.main.image.tag }}"
        imagePullPolicy: {{ .Values.airflow.main.image.pullPolicy }}
        ports:
        - name: webserver
          containerPort: 8080
        args: ["airflow", "webserver"]
        env:
        - name: AIRFLOW_KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: airflow-configmap
          mountPath: /root/airflow/airflow.cfg
          subPath: airflow.cfg
        - name: dags
          mountPath: /root/airflow/dags
      volumes:
      - name: dags
        persistentVolumeClaim:
          claimName: '{{ template "airflow.fullname" . }}-dags'
      - name: airflow-configmap
        configMap:
          name:  '{{ template "airflow.fullname" . }}-main'
---
apiVersion: v1
kind: Service
metadata:
  name: airflow
  namespace: airflow
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30809
  selector:
    name: airflow
