apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: airflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        imagePullPolicy: IfNotPresent
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        hostPath:
          path: /data/airflow/mysql
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: airflow
spec:
  ports:
  - port: 3306
    targetPort: mysql
  selector:
    app: mysql
