dags:
  nfs:
    path: /data/nfs/dags
    server: 10.0.0.3
    size: 100Mi
db:
  sql_alchemy_conn:
    enable: false
    value: 'postgresql+psycopg2://root:root@10.0.0.3:5432/airflow'
  postgres:
    enable: true
    resources:
      requests:
        cpu: ".5"
        memory: ".5Gi"
    persistence:
      data:
        enable: false
        accessMode: ReadWriteOnce
        size: "100Mi"
        storageClass: "cbs"
    image:
      repository: postgres
      tag: latest
      pullPolicy: IfNotPresent
    #resources:
      #limits:
        #cpu: "1"
        ## memory: "1024Mi"
      #requests:
        #cpu: "1"
        #memory: "1Gi"

airflow_image:
  repository: ccr.ccs.tencentyun.com/apache/airflow
  tag: dev
  pullPolicy: Always
airflow_worker_image:
  repository: ccr.ccs.tencentyun.com/apache/airflow
  tag: dev
  pullPolicy: Always

logging_backend:
  nfs:
    enable: true
    path: /data/nfs/logs
    server: 10.0.0.3
    size: 100Mi
  cos:
    enable: false
    secret_id: ''
    secret_key: ''
    region: ''
    bucket: ''

